### PR TITLE
update to swift 4

### PR DESCRIPTION
**Pull request by bcamarda**
@yavinfour 
@Nadohs

### CODE REVIEW

**Comment by Nadohs** [comment]
blaaah, I dont have `write access` so can't merge your PR :(

**Review by roymckenzie — APPROVED** [review]
Nice, Brett. Thanks!

**Comment by yavinfour** [comment]
Oh, I don't have write access either.

**Comment by Nadohs** [comment]
did it get merged in?

**Comment by Nadohs** [comment]
@georgedyjr i think probably you are the only one with write access right now

**Pull request merged**
